# Generated by Django 4.2 on 2023-05-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=255)),
                ('name_oc', models.CharField(max_length=255)),
                ('volume_memory', models.IntegerField(blank=True, null=True)),
                ('on_sale', models.BooleanField(default=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('dc', models.DateTimeField(auto_now_add=True)),
                ('du', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='core.company')),
                ('shop', models.ManyToManyField(blank=True, to='core.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_owner', models.CharField(max_length=255)),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='core.phone')),
            ],
        ),
    ]
