# Generated by Django 4.2 on 2023-05-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_phone_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('id',), 'verbose_name': 'Компанию', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ('dc', 'phone_name'), 'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='dc',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name_oc',
            field=models.CharField(max_length=255, verbose_name='Название ОС'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='on_sale',
            field=models.BooleanField(default=True, verbose_name='В продаже'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_name',
            field=models.CharField(max_length=255, verbose_name='Модель телефона'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='shop',
            field=models.ManyToManyField(blank=True, to='core.shop', verbose_name='В магазинах'),
        ),
    ]
